from enum import Enum


class AuthLogEvent(Enum):
    LOGIN_SUCCESSFUL = "SUCCESSFUL"
    LOGIN_FAILED = "FAILED"
    TOKEN_VALIDATED = "VALID_TOKEN"
    VALIDATION_TOKEN = "VALIDATION_TOKEN"
    EXPIRED_TOKEN = "EXPIRED_TOKEN"
    UNKNOWN = "UNKNOWN"


class Level(Enum):
    INFO = "INFO"


class FailureCause(Enum):
    NONE = "SUCCESSFUL"
    WRONG_CREDENTIALS = "WRONG_CREDENTIALS"
    EXPIRED_TOKEN = "EXPIRED_TOKEN"
    BLOCKED_USER = "BLOCKED_USER"
    UNKNOWN = "UNKNOWN"


